import { LOCAL_DESTINATION_IMAGES, getPackageGalleryImages } from "./local-images";

export interface Trip {
  id: string;
  title: string;
  location: string;
  duration: string;
  startDate: string;
  endDate: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  spotsLeft: number;
  totalSpots: number;
  image: string;
  images?: string[]; // Multiple images for slider
  tags: string[];
  category: "Couples" | "Girls Only" | "Boys Only" | "Mixed" | "Family";
  packageType: "3D2N" | "4D3N";
  description: string;
}

export const TRIPS: Trip[] = [
  // 3D2N Batches (Source: trippyway2.json)
  {
    id: "3d2n-dec22-couples",
    title: "Romantic Manali Escape",
    location: "Manali, Himachal Pradesh",
    duration: "3 Days / 2 Nights",
    startDate: "Dec 22",
    endDate: "Dec 24",
    price: 7999,
    originalPrice: 12999,
    rating: 4.9,
    reviews: 124,
    spotsLeft: 3,
    totalSpots: 20,
    image: LOCAL_DESTINATION_IMAGES.manali.romantic,
    images: [
      LOCAL_DESTINATION_IMAGES.manali.romantic,
      LOCAL_DESTINATION_IMAGES.manali.village,
      LOCAL_DESTINATION_IMAGES.manali.valleyView,
      LOCAL_DESTINATION_IMAGES.manali.winter,
      LOCAL_DESTINATION_IMAGES.manali.mountains,
    ],
    tags: ["Weekend favourite", "Couples Only"],
    category: "Couples",
    packageType: "3D2N",
    description:
      "A romantic getaway with candlelight dinners and private bonfires.",
  },
  {
    id: "3d2n-dec23-girls",
    title: "Christmas Eve Girls Gang",
    location: "Manali, Himachal Pradesh",
    duration: "3 Days / 2 Nights",
    startDate: "Dec 23",
    endDate: "Dec 25",
    price: 6999,
    originalPrice: 10999,
    rating: 4.8,
    reviews: 89,
    spotsLeft: 5,
    totalSpots: 25,
    image: LOCAL_DESTINATION_IMAGES.kalpa.aerial,
    images: [
      LOCAL_DESTINATION_IMAGES.kalpa.aerial,
      LOCAL_DESTINATION_IMAGES.manali.village,
      LOCAL_DESTINATION_IMAGES.manali.valley,
      LOCAL_DESTINATION_IMAGES.kullu.spring,
      LOCAL_DESTINATION_IMAGES.manali.valleyView,
    ],
    tags: ["Safe Travel", "Girls Only"],
    category: "Girls Only",
    packageType: "3D2N",
    description:
      "Safe, empowering, and fun - the ultimate girls trip for Christmas.",
  },
  {
    id: "4d3n-dec28-girls",
    title: "Girls NYE Celebration",
    location: "Manali & Kasol",
    duration: "4 Days / 3 Nights",
    startDate: "Dec 28",
    endDate: "Dec 31",
    price: 8999,
    originalPrice: 13999,
    rating: 4.9,
    reviews: 92,
    spotsLeft: 4,
    totalSpots: 25,
    image: LOCAL_DESTINATION_IMAGES.kasol.houses,
    images: [
      LOCAL_DESTINATION_IMAGES.kasol.houses,
      LOCAL_DESTINATION_IMAGES.kasol.valley,
      LOCAL_DESTINATION_IMAGES.kalpa.aerial,
      LOCAL_DESTINATION_IMAGES.manali.village,
      LOCAL_DESTINATION_IMAGES.kullu.spring,
    ],
    tags: ["Almost Full", "Girls Only"],
    category: "Girls Only",
    packageType: "4D3N",
    description: "Ring in the New Year with your besties in the Himalayas.",
  },
  {
    id: "3d2n-dec25-mixed",
    title: "Post-Christmas Fun",
    location: "Manali, Himachal Pradesh",
    duration: "3 Days / 2 Nights",
    startDate: "Dec 25",
    endDate: "Dec 27",
    price: 5999,
    originalPrice: 9999,
    rating: 4.6,
    reviews: 210,
    spotsLeft: 15,
    totalSpots: 40,
    image: LOCAL_DESTINATION_IMAGES.manali.winter,
    images: [
      LOCAL_DESTINATION_IMAGES.manali.winter,
      LOCAL_DESTINATION_IMAGES.manali.mountains,
      LOCAL_DESTINATION_IMAGES.kullu.spring,
      LOCAL_DESTINATION_IMAGES.manali.village,
      LOCAL_DESTINATION_IMAGES.manali.valleyView,
    ],
    tags: ["Budget Friendly", "Mixed Group"],
    category: "Mixed",
    packageType: "3D2N",
    description: "Meet new people and celebrate the festive season in Manali.",
  },
  // 4D3N Batches (Source: trippyway2.json)
  {
    id: "4d3n-dec26-couples",
    title: "Romantic NYE Celebration",
    location: "Manali & Kasol",
    duration: "4 Days / 3 Nights",
    startDate: "Dec 26",
    endDate: "Dec 29",
    price: 9999,
    originalPrice: 15999,
    rating: 5.0,
    reviews: 45,
    spotsLeft: 2,
    totalSpots: 15,
    image: LOCAL_DESTINATION_IMAGES.manali.village,
    images: [
      LOCAL_DESTINATION_IMAGES.manali.village,
      LOCAL_DESTINATION_IMAGES.kasol.valley,
      LOCAL_DESTINATION_IMAGES.manali.romantic,
      LOCAL_DESTINATION_IMAGES.kasol.mountains,
      LOCAL_DESTINATION_IMAGES.manali.valleyView,
    ],
    tags: ["Selling Fast", "Couples Only"],
    category: "Couples",
    packageType: "4D3N",
    description: "The perfect romantic start to the New Year with Kasol vibes.",
  },
  {
    id: "4d3n-dec27-mixed",
    title: "Pre-NYE Party Vibes",
    location: "Manali & Kasol",
    duration: "4 Days / 3 Nights",
    startDate: "Dec 27",
    endDate: "Dec 30",
    price: 8499,
    originalPrice: 13499,
    rating: 4.8,
    reviews: 150,
    spotsLeft: 20,
    totalSpots: 50,
    image: LOCAL_DESTINATION_IMAGES.kasol.valley,
    images: [
      LOCAL_DESTINATION_IMAGES.kasol.valley,
      LOCAL_DESTINATION_IMAGES.kasol.houses,
      LOCAL_DESTINATION_IMAGES.manali.valley,
      LOCAL_DESTINATION_IMAGES.kullu.spring,
      LOCAL_DESTINATION_IMAGES.manali.village,
    ],
    tags: ["Party", "Mixed Group"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "Get the party started early with this high-energy group trip.",
  },
  {
    id: "3d2n-dec24-boys",
    title: "Christmas Adventure Boys",
    location: "Manali, Himachal Pradesh",
    duration: "3 Days / 2 Nights",
    startDate: "Dec 24",
    endDate: "Dec 26",
    price: 6499,
    originalPrice: 10499,
    rating: 4.7,
    reviews: 56,
    spotsLeft: 12,
    totalSpots: 30,
    image: LOCAL_DESTINATION_IMAGES.highAltitude.pass,
    images: [
      LOCAL_DESTINATION_IMAGES.highAltitude.pass,
      LOCAL_DESTINATION_IMAGES.highAltitude.mountains,
      LOCAL_DESTINATION_IMAGES.highAltitude.panoramic,
      LOCAL_DESTINATION_IMAGES.manali.winter,
      LOCAL_DESTINATION_IMAGES.manali.mountains,
    ],
    tags: ["Adventure", "Boys Only"],
    category: "Boys Only",
    packageType: "3D2N",
    description:
      "Brotherhood, adventure, and Christmas celebrations in the mountains.",
  },

  {
    id: "4d3n-dec29-boys",
    title: "Boys NYE Adventure",
    location: "Manali & Kasol",
    duration: "4 Days / 3 Nights",
    startDate: "Dec 29",
    endDate: "Jan 1",
    price: 8999,
    originalPrice: 14499,
    rating: 4.7,
    reviews: 67,
    spotsLeft: 8,
    totalSpots: 30,
    image: LOCAL_DESTINATION_IMAGES.highAltitude.mountains,
    images: [
      LOCAL_DESTINATION_IMAGES.highAltitude.mountains,
      LOCAL_DESTINATION_IMAGES.highAltitude.pass,
      LOCAL_DESTINATION_IMAGES.highAltitude.panoramic,
      LOCAL_DESTINATION_IMAGES.kasol.valley,
      LOCAL_DESTINATION_IMAGES.manali.winter,
    ],
    tags: ["Limited Seats", "Boys Only"],
    category: "Boys Only",
    packageType: "4D3N",
    description: "An epic start to 2025 with adventure and brotherhood.",
  },
  {
    id: "4d3n-dec30-mixed",
    title: "Last Minute NYE Magic",
    location: "Manali & Kasol",
    duration: "4 Days / 3 Nights",
    startDate: "Dec 30",
    endDate: "Jan 2",
    price: 7999,
    originalPrice: 12999,
    rating: 4.6,
    reviews: 45,
    spotsLeft: 25,
    totalSpots: 50,
    image: LOCAL_DESTINATION_IMAGES.kullu.spring,
    images: [
      LOCAL_DESTINATION_IMAGES.kullu.spring,
      LOCAL_DESTINATION_IMAGES.kullu.valley,
      LOCAL_DESTINATION_IMAGES.manali.valley,
      LOCAL_DESTINATION_IMAGES.kasol.valley,
      LOCAL_DESTINATION_IMAGES.manali.village,
    ],
    tags: ["Available", "Mixed Group"],
    category: "Mixed",
    packageType: "4D3N",
    description: "Celebrate the New Year in the heart of the mountains.",
  },

  // Mahakumbh 2025 Packages - Varanasi, Prayagraj & Ayodhya
  {
    id: "3d2n-jan10-mahakumbh-mixed",
    title: "Mahakumbh Divine Experience",
    location: "Prayagraj & Varanasi",
    duration: "3 Days / 2 Nights",
    startDate: "Jan 10",
    endDate: "Jan 12",
    price: 6999,
    originalPrice: 11499,
    rating: 4.9,
    reviews: 142,
    spotsLeft: 8,
    totalSpots: 30,
    image:
      "https://images.unsplash.com/photo-1532375810709-75b1da00537c?q=80&w=1400&auto=format&fit=crop",
    tags: ["Mahakumbh 2025", "Spiritual"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Experience the sacred Mahakumbh 2025 with holy dips at Triveni Sangam and evening Ganga Aarti at Varanasi ghats.",
  },
  {
    id: "3d2n-jan15-mahakumbh-family",
    title: "Sacred Mahakumbh Family Journey",
    location: "Prayagraj & Varanasi",
    duration: "3 Days / 2 Nights",
    startDate: "Jan 15",
    endDate: "Jan 17",
    price: 6499,
    originalPrice: 10999,
    rating: 4.8,
    reviews: 98,
    spotsLeft: 12,
    totalSpots: 35,
    image:
      "https://images.unsplash.com/photo-1582719471137-c3967ffb1c42?q=80&w=1400&auto=format&fit=crop",
    tags: ["Family Friendly", "Spiritual"],
    category: "Family",
    packageType: "3D2N",
    description:
      "Family-friendly pilgrimage to Mahakumbh with comfortable accommodations and guided temple visits.",
  },
  {
    id: "3d2n-jan20-mahakumbh-couples",
    title: "Spiritual Getaway - Mahakumbh",
    location: "Prayagraj & Varanasi",
    duration: "3 Days / 2 Nights",
    startDate: "Jan 20",
    endDate: "Jan 22",
    price: 7499,
    originalPrice: 12499,
    rating: 4.9,
    reviews: 67,
    spotsLeft: 6,
    totalSpots: 20,
    image:
      "https://images.unsplash.com/photo-1609920658906-8223bd289001?q=80&w=1400&auto=format&fit=crop",
    tags: ["Couples Only", "Spiritual"],
    category: "Couples",
    packageType: "3D2N",
    description:
      "Seek divine blessings together at Mahakumbh with serene boat rides and peaceful temple visits.",
  },
  {
    id: "4d3n-jan12-mahakumbh-ayodhya-mixed",
    title: "Complete Spiritual Circuit - Mahakumbh & Ayodhya",
    location: "Prayagraj, Varanasi & Ayodhya",
    duration: "4 Days / 3 Nights",
    startDate: "Jan 12",
    endDate: "Jan 15",
    price: 9999,
    originalPrice: 15999,
    rating: 5.0,
    reviews: 156,
    spotsLeft: 5,
    totalSpots: 35,
    image:
      "https://images.unsplash.com/photo-1598077550687-c854e50d8afc?q=80&w=1400&auto=format&fit=crop",
    tags: ["Selling Fast", "Complete Circuit"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "The ultimate spiritual journey covering Mahakumbh, Varanasi's ancient ghats, and the newly inaugurated Ram Mandir in Ayodhya.",
  },
  {
    id: "4d3n-jan18-mahakumbh-ayodhya-family",
    title: "Holy Trinity - Prayagraj, Varanasi & Ayodhya",
    location: "Prayagraj, Varanasi & Ayodhya",
    duration: "4 Days / 3 Nights",
    startDate: "Jan 18",
    endDate: "Jan 21",
    price: 9499,
    originalPrice: 15499,
    rating: 4.9,
    reviews: 124,
    spotsLeft: 10,
    totalSpots: 40,
    image:
      "https://images.unsplash.com/photo-1585131349129-e68173d2e3b4?q=80&w=1400&auto=format&fit=crop",
    tags: ["Family Friendly", "Complete Circuit"],
    category: "Family",
    packageType: "4D3N",
    description:
      "Comprehensive family pilgrimage with Mahakumbh holy dip, Kashi Vishwanath darshan, and Ram Mandir visit with comfortable stays.",
  },
  {
    id: "4d3n-jan25-mahakumbh-ayodhya-couples",
    title: "Divine Romance - Mahakumbh Special",
    location: "Prayagraj, Varanasi & Ayodhya",
    duration: "4 Days / 3 Nights",
    startDate: "Jan 25",
    endDate: "Jan 28",
    price: 10999,
    originalPrice: 17999,
    rating: 4.8,
    reviews: 89,
    spotsLeft: 7,
    totalSpots: 25,
    image:
      "https://images.unsplash.com/photo-1516542076529-1ea3854896f2?q=80&w=1400&auto=format&fit=crop",
    tags: ["Couples Only", "Luxury"],
    category: "Couples",
    packageType: "4D3N",
    description:
      "Premium spiritual experience for couples with heritage hotels, private boat rides, and exclusive darshan arrangements.",
  },
  {
    id: "4d3n-feb01-mahakumbh-ayodhya-mixed",
    title: "Mauni Amavasya Special - Mahakumbh",
    location: "Prayagraj, Varanasi & Ayodhya",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 1",
    endDate: "Feb 4",
    price: 11999,
    originalPrice: 18999,
    rating: 5.0,
    reviews: 203,
    spotsLeft: 3,
    totalSpots: 50,
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1400&auto=format&fit=crop",
    tags: ["Almost Full", "Mauni Amavasya"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "Experience the most auspicious bathing day at Mahakumbh - Mauni Amavasya, with complete spiritual circuit including Ayodhya Ram Mandir.",
  },
  {
    id: "3d2n-jan28-varanasi-ayodhya-mixed",
    title: "Kashi Ayodhya Express",
    location: "Varanasi & Ayodhya",
    duration: "3 Days / 2 Nights",
    startDate: "Jan 28",
    endDate: "Jan 30",
    price: 5999,
    originalPrice: 9999,
    rating: 4.7,
    reviews: 112,
    spotsLeft: 15,
    totalSpots: 40,
    image:
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1400&auto=format&fit=crop",
    tags: ["Budget Friendly", "Quick Trip"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Perfect weekend spiritual getaway covering the ancient city of Varanasi and the sacred Ram Janmabhoomi in Ayodhya.",
  },

  // ========================================================================
  // THEME-BASED PACKAGES
  // ========================================================================

  // ROMANTIC ESCAPE - Create Unforgettable Moments Together
  {
    id: "3d2n-feb10-udaipur-romantic",
    title: "Royal Udaipur Romance",
    location: "Udaipur, Rajasthan",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 10",
    endDate: "Feb 12",
    price: 11999,
    originalPrice: 18999,
    rating: 4.9,
    reviews: 187,
    spotsLeft: 6,
    totalSpots: 20,
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1400&auto=format&fit=crop",
    tags: ["Romantic Escape", "Luxury"],
    category: "Couples",
    packageType: "3D2N",
    description:
      "Experience royal romance in the City of Lakes with heritage palace stays, private boat rides on Lake Pichola, candlelight dinners, and sunset views at City Palace.",
  },
  {
    id: "4d3n-feb14-goa-romantic",
    title: "Valentine's Beach Romance in Goa",
    location: "Goa",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 14",
    endDate: "Feb 17",
    price: 12999,
    originalPrice: 19999,
    rating: 5.0,
    reviews: 234,
    spotsLeft: 4,
    totalSpots: 15,
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1400&auto=format&fit=crop",
    tags: ["Romantic Escape", "Valentine Special"],
    category: "Couples",
    packageType: "4D3N",
    description:
      "Celebrate love on pristine beaches with beachside candlelight dinners, couple spa sessions, private yacht cruise, and romantic sunset at Chapora Fort.",
  },
  {
    id: "4d3n-feb20-kashmir-romantic",
    title: "Kashmir - Paradise for Two",
    location: "Srinagar & Gulmarg, Kashmir",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 20",
    endDate: "Feb 23",
    price: 14999,
    originalPrice: 22999,
    rating: 4.9,
    reviews: 156,
    spotsLeft: 5,
    totalSpots: 18,
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1400&auto=format&fit=crop",
    tags: ["Romantic Escape", "Mountain Romance"],
    category: "Couples",
    packageType: "4D3N",
    description:
      "Romantic escape to paradise on earth with houseboat stay on Dal Lake, shikara rides, snow activities in Gulmarg, and Mughal garden visits.",
  },

  // DESIGNER & PHOTOGRAPHER - Capture India's Most Photogenic Landscapes
  {
    id: "3d2n-feb08-jaisalmer-photo",
    title: "Golden Jaisalmer Photo Expedition",
    location: "Jaisalmer, Rajasthan",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 8",
    endDate: "Feb 10",
    price: 8999,
    originalPrice: 14499,
    rating: 4.8,
    reviews: 143,
    spotsLeft: 10,
    totalSpots: 25,
    image:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1400&auto=format&fit=crop",
    tags: ["Photography", "Content Creation"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Capture golden sand dunes, majestic forts, and desert sunsets with professional photography guide. Includes sunrise desert shoot, fort exploration, and camel safari photoshoot.",
  },
  {
    id: "4d3n-feb12-hampi-photo",
    title: "Ancient Hampi Visual Journey",
    location: "Hampi, Karnataka",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 12",
    endDate: "Feb 15",
    price: 9499,
    originalPrice: 15499,
    rating: 5.0,
    reviews: 198,
    spotsLeft: 8,
    totalSpots: 30,
    image:
      "https://images.unsplash.com/photo-1582639510494-c80b5de9f148?q=80&w=1400&auto=format&fit=crop",
    tags: ["Photography", "Heritage"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "Photograph UNESCO World Heritage ruins, boulder landscapes, and ancient temples. Perfect for content creators with golden hour shoots, drone-friendly locations, and unique backdrops.",
  },
  {
    id: "3d2n-feb18-rishikesh-photo",
    title: "Rishikesh Adventure Frames",
    location: "Rishikesh, Uttarakhand",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 18",
    endDate: "Feb 20",
    price: 7499,
    originalPrice: 12499,
    rating: 4.7,
    reviews: 167,
    spotsLeft: 12,
    totalSpots: 35,
    image: LOCAL_DESTINATION_IMAGES.highAltitude.panoramic,
    tags: ["Photography", "Adventure"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Capture river rafting action shots, yoga poses at sunrise, Ganga Aarti, and Himalayan landscapes. Ideal for adventure and lifestyle content creators.",
  },

  // PROFESSIONAL PLANNING - Elevate Your Team with Strategic Retreats
  {
    id: "3d2n-feb05-lonavala-corporate",
    title: "Lonavala Team Building Retreat",
    location: "Lonavala, Maharashtra",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 5",
    endDate: "Feb 7",
    price: 9499,
    originalPrice: 15499,
    rating: 4.8,
    reviews: 89,
    spotsLeft: 20,
    totalSpots: 50,
    image:
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1400&auto=format&fit=crop",
    tags: ["Corporate Retreat", "Team Building"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Professional retreat with conference facilities, team building activities, strategy workshops, and motivational sessions in peaceful hill station setting.",
  },
  {
    id: "4d3n-feb15-coorg-corporate",
    title: "Coorg Leadership Development",
    location: "Coorg, Karnataka",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 15",
    endDate: "Feb 18",
    price: 11999,
    originalPrice: 18999,
    rating: 4.9,
    reviews: 112,
    spotsLeft: 15,
    totalSpots: 40,
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1400&auto=format&fit=crop",
    tags: ["Corporate Retreat", "Leadership"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "Strategic planning retreat in coffee plantations with leadership workshops, brainstorming sessions, outdoor team challenges, and networking dinners.",
  },
  {
    id: "3d2n-feb22-pondicherry-corporate",
    title: "Pondicherry Innovation Retreat",
    location: "Pondicherry",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 22",
    endDate: "Feb 24",
    price: 8499,
    originalPrice: 13999,
    rating: 4.7,
    reviews: 94,
    spotsLeft: 18,
    totalSpots: 45,
    image:
      "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=1400&auto=format&fit=crop",
    tags: ["Corporate Retreat", "Innovation"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Creative thinking retreat in French heritage town with innovation workshops, beach team activities, heritage walks, and professional networking sessions.",
  },

  // THEATER & PERFORMING ARTS - Immerse in India's Cultural Heartbeat
  {
    id: "3d2n-feb07-delhi-cultural",
    title: "Delhi Cultural Heritage Tour",
    location: "Delhi",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 7",
    endDate: "Feb 9",
    price: 7499,
    originalPrice: 12499,
    rating: 4.8,
    reviews: 176,
    spotsLeft: 14,
    totalSpots: 40,
    image:
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1400&auto=format&fit=crop",
    tags: ["Cultural Arts", "Heritage"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Explore theater shows at NCPA, visit National Museum, experience street performances at Dilli Haat, heritage walks through Old Delhi, and traditional dance performances.",
  },
  {
    id: "4d3n-feb16-mumbai-cultural",
    title: "Mumbai Performing Arts Experience",
    location: "Mumbai, Maharashtra",
    duration: "4 Days / 3 Nights",
    startDate: "Feb 16",
    endDate: "Feb 19",
    price: 10999,
    originalPrice: 17499,
    rating: 4.9,
    reviews: 201,
    spotsLeft: 10,
    totalSpots: 35,
    image:
      "https://images.unsplash.com/photo-1566552881560-0be862a7c445?q=80&w=1400&auto=format&fit=crop",
    tags: ["Cultural Arts", "Theater"],
    category: "Mixed",
    packageType: "4D3N",
    description:
      "Bollywood studio tour, theater performances at Prithvi Theatre, art gallery visits, classical music concerts, and meet artists in the entertainment capital.",
  },
  {
    id: "3d2n-feb25-chennai-cultural",
    title: "Chennai Classical Arts Journey",
    location: "Chennai, Tamil Nadu",
    duration: "3 Days / 2 Nights",
    startDate: "Feb 25",
    endDate: "Feb 27",
    price: 7999,
    originalPrice: 13499,
    rating: 4.9,
    reviews: 143,
    spotsLeft: 12,
    totalSpots: 30,
    image:
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=1400&auto=format&fit=crop",
    tags: ["Cultural Arts", "Classical Performance"],
    category: "Mixed",
    packageType: "3D2N",
    description:
      "Experience Bharatanatyam performances, Carnatic music concerts, temple architecture tours, traditional Kolam art workshops, and meet renowned classical artists.",
  },
];

export const FILTERS = {
  categories: ["All", "Couples", "Girls Only", "Boys Only", "Mixed"],
  durations: ["All", "3D2N", "4D3N"],
};
